server:
    port: 8080

spring:
    profiles:
        active: dev
        
# DataSource settings: set here configurations for the database connection
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/formulaone
        schema: formulaone
        username: postgres
        password: postgres

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
          ddl-auto: none  
          naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: true
          hibernate.id.new_generator_mappings: true
          
        

# LIQUIBASE (LiquibaseProperties)
liquibase:
  change-log: classpath:config/liquibase/master.xml
  contexts: dev
  drop-first: false

#Logging parameters
logging:
  path: c:/logs
  file: formulaone.log 

